# Generated by Django 4.1.3 on 2022-12-12 06:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil', verbose_name='Foto de Perfil')),
                ('password2', models.CharField(default='', max_length=62, verbose_name='Verfica tu contraseña')),
                ('direccion', models.CharField(blank=True, default='', max_length=255, verbose_name='Direccion')),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Codigo Postal')),
                ('telefono', models.CharField(default='', max_length=10, verbose_name='Telefono')),
                ('puede_vender', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Vendedor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil', verbose_name='Foto de Perfil')),
                ('direccion', models.CharField(default='', max_length=255, verbose_name='Direccion')),
                ('telefono', models.CharField(default='', max_length=10, verbose_name='Telefono')),
                ('nombre_negocio', models.CharField(default='', max_length=255, verbose_name='Nombre negocio')),
                ('foto_fachada', models.ImageField(blank=True, null=True, upload_to='negocios', verbose_name='Foto de Fachada de negocio')),
                ('rfc', models.CharField(default='', max_length=13, verbose_name='RFC')),
                ('password_rev', models.CharField(default='', max_length=62, verbose_name='Verifica tu contraseña')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
                ('client_id', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Client Paypal Id')),
                ('vende', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estado', verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Questions', models.TextField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
