# Generated by Django 3.2.8 on 2021-11-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password2',
            field=models.CharField(
                default='', max_length=62, verbose_name='Verfica tu contraseña'),
        ),
    ]
