# Generated by Django 2.2.14 on 2022-03-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20220309_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario_vendedor',
            old_name='foto_perfil',
            new_name='foto',
        ),
    ]
