# Generated by Django 3.2.8 on 2021-12-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_vendedor',
            name='password_rev',
            field=models.CharField(default='', max_length=62, verbose_name='Verifica tu contraseña'),
        ),
    ]
