# Generated by Django 3.2.8 on 2021-12-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_vendedor_password_rev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='usuario_vendedor',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usuario_vendedor',
            name='municipio',
        ),
    ]
