# Generated by Django 3.2.8 on 2022-05-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20220511_0519'),
        ('usuarios', '0005_auto_20220523_1637'),
    ]

    operations = [
    ]
