# Generated by Django 4.1.3 on 2022-11-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20220523_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_vendedor',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Client Paypal Id'),
        ),
    ]
