# Generated by Django 3.2.8 on 2021-12-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20211206_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_vendedor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles', verbose_name='Foto de Perfil'),
        ),
    ]
