# Generated by Django 3.2.8 on 2021-12-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20211206_2124'),
        ('usuarios', '0005_auto_20211206_2337'),
    ]

    operations = [
    ]
