# Generated by Django 4.1.4 on 2022-12-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_vendedor_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Codigo Postal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='', max_length=10, verbose_name='Telefono'),
        ),
    ]
