# Generated by Django 4.1.3 on 2022-12-11 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20220418_1311'),
        ('usuarios', '0007_usuario_codigo_postal_usuario_direccion_and_more'),
    ]

    operations = [
    ]
