# Generated by Django 4.1.4 on 2022-12-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_merge_20221211_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_vendedor',
            name='vende',
            field=models.BooleanField(default=False),
        ),
    ]
