# Generated by Django 4.1.4 on 2022-12-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_vendedor_vende'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_vendedor',
            name='foto_Fachada',
            field=models.ImageField(blank=True, null=True, upload_to='negocios', verbose_name='Foto de Fachada'),
        ),
        migrations.AddField(
            model_name='usuario_vendedor',
            name='nombre_negocio',
            field=models.CharField(default='', max_length=255, verbose_name='Nombre negocio'),
        ),
        migrations.AddField(
            model_name='usuario_vendedor',
            name='rfc',
            field=models.CharField(default='', max_length=13, verbose_name='RFC'),
        ),
    ]
