# Generated by Django 4.1.4 on 2022-12-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_merge_20221210_1906'),
        ('usuarios', '0010_usuario_vendedor_foto_fachada_and_more'),
    ]

    operations = [
    ]
