# Generated by Django 3.2.8 on 2021-10-30 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='usuarios.usuario', verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='usuarios.usuario', verbose_name='Vendedor'),
        ),
    ]
