# Generated by Django 4.1.2 on 2022-11-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.categoria', verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
