# Generated by Django 3.2.8 on 2021-11-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
    ]
