# Generated by Django 4.1.3 on 2022-11-21 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_vendedor_client_id'),
        ('principal', '0003_auto_20220523_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario_vendedor', verbose_name='Vendedor'),
        ),
    ]
