# Generated by Django 3.2.8 on 2021-12-05 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_vendedor_password_rev'),
        ('principal', '0003_auto_20211119_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='usuarios.usuario_vendedor', verbose_name='Vendedor'),
        ),
    ]
