# Generated by Django 4.1.2 on 2022-11-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_producto_vendedor_servicio_vendedor_and_more'),
        ('principal', '0004_alter_producto_vendedor'),
    ]

    operations = [
    ]
