# Generated by Django 3.2.8 on 2022-05-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_merge_0003_auto_20220511_0519_0003_auto_20220523_1637'),
        ('principal', '0004_remove_producto_slug'),
    ]

    operations = [
    ]
