# Generated by Django 4.1.4 on 2022-12-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20220418_1311'),
        ('principal', '0005_merge_20221128_1801'),
    ]

    operations = [
    ]
