# Generated by Django 4.1.4 on 2022-12-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_merge_20221210_1906'),
        ('principal', '0007_remove_categoria_slug_remove_producto_slug'),
    ]

    operations = [
    ]
