# Generated by Django 3.2.8 on 2022-03-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20211207_0439'),
        ('principal', '0008_categoria_slug'),
    ]

    operations = [
    ]
