# Generated by Django 2.2.14 on 2022-03-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.FloatField(verbose_name='Precio unitario')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_orden', models.DateTimeField()),
                ('ordenado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoOrdenado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenado', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
    ]
