# Generated by Django 4.1.3 on 2022-12-11 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_auto_20220418_1311'),
        ('ordenes', '0003_auto_20220523_1637'),
    ]

    operations = [
    ]
