# Generated by Django 4.1.3 on 2022-12-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_merge_0003_auto_20220418_1311_0003_auto_20220523_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_orden',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
